/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
/**
 * @autor Jeremy Prieto
 */
import javax.swing.JOptionPane;

/**
 *
 * @author WUSUARIO
 */
public class frmEjercicio5 extends javax.swing.JFrame {

    /**
     * Creates new form frmEjercicio5
     */
    public frmEjercicio5() {
        initComponents();
        n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de regsitros"));
        setLocationRelativeTo(this);
        setSize(400,300);
    }
    
    //VARIABLE GLOBALES
    int i=1,n;
    String nom1="",nom2="",nom3="";
    int num1,num2,num3;
    int mayor = 0,mayor1=0,mayor2=0, menor=0,menor1=0,menor2=0,tp1=0,tp2=0,tp3=0,t1=0,t2=0,t3=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PRODUCCION DE OPERARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel2.setText("Numero:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setText("Sector:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setText("Piezas defectuozas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setText("Piezas no defectuozas:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el sector", "1", "2", "3" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 60, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jButton2.setText("Informar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel7.setText("...");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ingresar(int num, String nom, int s, int d,int nd){
        
        if(s==1){
            if (d > mayor){  // se compara la nota con la mayor y con la menor actual
                mayor = d;
                menor = d;
                nom1=nom;
                num1=num;
            } else if (d < menor) {
                menor = d;
            }
            tp1= tp1+ (d+nd);
            t1 += d;
            
        }
        if(s==2){
            if (d > mayor){  // se compara la nota con la mayor y con la menor actual
                mayor1 = d;
                menor1 = d;
                nom2=nom;
                num2=num;
            } else if (d < menor) {
                menor = d;
            }
            tp2= tp2+ (d+nd);
            t2 += d;
        }
        if(s==3){
            if (d > mayor){  // se compara la nota con la mayor y con la menor actual
                mayor2 = d;
                menor2 = d;
                nom3=nom;
                num3=num;
            } else if (d < menor) {
                menor = d;
            }
            tp3= tp3+ (d+nd);
            t3 += d;
        }
       
        borrar();
        
        jLabel7.setText(i +" de "+ n);
        if(i==n){
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
        }
    }
    
    public void borrar(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }
    
    public void calculo(){
        int m1 = (tp1 * (t1/100));
        int m2= (tp2 * (t2/100));
        int m3 =(tp3 * (t3/100));
        int mayo=m1,meno=m1; String g="1";
        if(m2>mayo){
            mayo+=m2;
            meno+=m2;
            g= "2";
        }else if(m2<meno){
            meno +=m2;
        }
        if(m3>mayo){
            mayo+=m3;
            meno+=m3;
            g= "3";
        }else if(m3<meno){
            meno +=m3;
        }
        
        JOptionPane.showMessageDialog(null, "Sector 1: " +nom1+" " + num1 + "\nSector2: "+nom2+" " + num2 + "\nSector3: "+nom3+" " + num3+"\nSector con >% de piezas defectuozas: "+ g );
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(i<=n){
            int numero = Integer.parseInt(jTextField1.getText());
            String nombre = jTextField2.getText();
            int sector = Integer.parseInt(jComboBox1.getSelectedItem().toString());
            int defec = Integer.parseInt(jTextField3.getText());
            int ndefec = Integer.parseInt(jTextField4.getText());
            
            ingresar(numero,nombre,sector,defec,ndefec);
            
            i++;
            
        }else{
            JOptionPane.showMessageDialog(null, "Llego al maximo de registros");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        calculo();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
