/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
/**
 * @autor Jeremy Prieto
 */
import javax.swing.JOptionPane;

/**
 *
 * @author WUSUARIO
 */
public class frmEjercicio6 extends javax.swing.JFrame {

    /**
     * Creates new form frmEjercicio6
     */
    public frmEjercicio6() {
        initComponents();
        n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de articulos"));
        setLocationRelativeTo(this);
        setSize(400,300);
    }
    
    //VARIABLES GLOBALES
    int i=1,n,total=0;
    String nom1="",nom2="",nom3="";
    int num1,num2,num3;
    int mayor = 0,mayor1=0,mayor2=0, menor=0,menor1=0,menor2=0,t1=0,t2=0,t3=0;
    
    
    public void eliminar(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ARTICULOS DE VENTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel2.setText("Numero:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setText("Clase:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "a", "b", "c" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel6.setText("...");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ingreso(int num, String nom, int p, String c){
        total += p;
        if(c.equals("a")){
            if (p > mayor){  // se compara la nota con la mayor y con la menor actual
                mayor = p;
                menor = p;
                nom1=nom;
                num1=num;
            } else if (p < menor) {
                menor = p;
            }
            
            t1 += p;
            
        }
        if(c.equals("b")){
            if (p > mayor){  // se compara la nota con la mayor y con la menor actual
                mayor1 = p;
                menor1 = p;
                nom2=nom;
                num2=num;
            } else if (p < menor) {
                menor = p;
            }
           
            t2 += p;
        }
        if(c.equals("c")){
            if (p > mayor){  // se compara la nota con la mayor y con la menor actual
                mayor2 = p;
                menor2 = p;
                nom3=nom;
                num3=num;
            } else if (p < menor) {
                menor = p;
            }
            
            t3 += p;
        }
       
        
        eliminar();
        jLabel6.setText(i+" de " + n);
        if(i == n){
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
           
        }
        
    }
    
    public void calcular(){
        int m1 = (t1 * (t1/100));
        int m2= (t2 * (t2/100));
        int m3 =(t3 * (t3/100));
        int mayo=m1,meno=m1; String g="a";
        if(m2>mayo){
            mayo+=m2;
            meno+=m2;
            g= "b";
        }else if(m2<meno){
            meno +=m2;
        }
        if(m3>mayo){
            mayo+=m3;
            meno+=m3;
            g= "c";
        }else if(m3<meno){
            meno +=m3;
        }

        JOptionPane.showMessageDialog(null, "Articulo mas caro: " +"\nClase a : "+nom1+" "+ num1+"\nClase b : "+nom2+" "+ num2+"\nClase c : "+nom3+" "+ num3+ "\nClase mayor promedio: "+g );
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(i<=n){
            int numero = Integer.parseInt(jTextField1.getText());
            String nombre = jTextField2.getText();
            int precio = Integer.parseInt(jTextField3.getText());
            String clase = jComboBox1.getSelectedItem().toString();
            
            ingreso(numero,nombre,precio,clase);
            
            i++;
        }else{
            JOptionPane.showMessageDialog(null, "Maximo de registro superado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        calcular();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
