/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the
 */
package Formularios;

import Entidades.Postulante_e7;
    import javax.swing.*;

/**
 *
 * @author WUSUARIO
 */
public class frmEjercicio7 extends javax.swing.JFrame {

    private DefaultListModel modelo1 =new DefaultListModel();
    private DefaultListModel modelo2 =new DefaultListModel();
    private DefaultListModel modelo3 =new DefaultListModel();
    private DefaultListModel modelo4 =new DefaultListModel();
    
    public double mayor;
    public double menor;
    public String postMay;
    public String postMen;

    public double getMayor() {
        return mayor;
    }

    public void setMayor(double mayor) {
        this.mayor = mayor;
    }

    public double getMenor() {
        return menor;
    }

    public void setMenor(double menor) {
        this.menor = menor;
    }

    public String getPostMay() {
        return postMay;
    }

    public void setPostMay(String postMay) {
        this.postMay = postMay;
    }

    public String getPostMen() {
        return postMen;
    }

    public void setPostMen(String postMen) {
        this.postMen = postMen;
    }
    
    
    
    
    /**
     * Creates new form frmEjercicio7
     */
    public frmEjercicio7() {
        initComponents();
        setLocationRelativeTo(this);
        setSize(410,500);
        this.setTitle("Postulante al Examen de Admision");
        lstPost.setModel(modelo1);
        lstBuenas.setModel(modelo2);
        lstMalas.setModel(modelo3);
        lstPuntaje.setModel(modelo4);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        txtPost.setEnabled(false);
        txtBien.setEnabled(false);
        txtMal.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPost = new javax.swing.JTextField();
        txtBien = new javax.swing.JTextField();
        txtMal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPost = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstBuenas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMalas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPuntaje = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Postulante:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setText("Preguntas Bien contestadas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Preguntas Mal contestadas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(txtPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 260, -1));
        getContentPane().add(txtBien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 160, -1));
        getContentPane().add(txtMal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, -1));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        lstPost.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPost.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPostValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPost);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 200));

        jScrollPane2.setViewportView(lstBuenas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 60, 200));

        jScrollPane3.setViewportView(lstMalas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 60, 200));

        jScrollPane4.setViewportView(lstPuntaje);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 60, 200));

        jLabel4.setText("Postulante");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setText("Buenas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel6.setText("Malas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel7.setText("Puntaje");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void nuevo(){
        txtPost.setEnabled(true);
        txtBien.setEnabled(true);
        txtMal.setEnabled(true);
        txtPost.setText("");
        txtBien.setText("");
        txtMal.setText("");
        txtPost.requestFocus();
        jButton2.setEnabled(true);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nuevo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//        double puntaje;
        int buenas = Integer.parseInt(txtBien.getText());
        int malas = Integer.parseInt(txtMal.getText());
//        puntaje = (double) buenas*4.8 - (double)malas*1.04;
        String nombre  = txtPost.getText();
        Postulante_e7 op = new Postulante_e7(nombre, buenas, malas);
        
        if((buenas+malas)<=100){
            modelo1.addElement(op.getNombre());
            modelo2.addElement(String.valueOf(op.getPbien()));
            modelo3.addElement(String.valueOf(op.getPmal()));
            modelo4.addElement(String.valueOf(op.Puntaje()));
            jButton2.setEnabled(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Las preguntas bien y mal constadas no debe superar los 100 puntos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lstPostValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPostValueChanged
        int indice;
        indice = lstPost.getSelectedIndex();
        lstBuenas.setSelectedIndex(indice);
        lstMalas.setSelectedIndex(indice);
        lstPuntaje.setSelectedIndex(indice);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_lstPostValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int indice;
        indice = lstPost.getSelectedIndex();
        modelo1.remove(indice);
        modelo2.remove(indice);
        modelo3.remove(indice);
        modelo4.remove(indice);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int cuenta,i=0,posmayor=-1,posmenor=-1;
        double may=0,men=500,p;
        String pmay,pmen;
        cuenta = modelo4.getSize();
        if(cuenta>=1){
            for(i=0;i<cuenta;i++){
                p=Double.parseDouble((String)modelo4.getElementAt(i));
                if(p>may){
                    may=p;
                    posmayor=i;
                }
                if(p<men){
                    men=p;
                    posmenor=i;
                }
            }
            setMayor(may);
            setMenor(men);
            pmay=(String)modelo1.elementAt(posmayor);
            pmen=(String)modelo1.elementAt(posmenor);
            setPostMay(pmay);
            setPostMen(pmen);
            frmEjercicio7_1 form2 = new frmEjercicio7_1();
            form2.mayor=getMayor();
            form2.menor=getMenor();
            form2.postMay=getPostMay();
            form2.postMen=getPostMen();
            form2.show();;
            
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstBuenas;
    private javax.swing.JList<String> lstMalas;
    private javax.swing.JList<String> lstPost;
    private javax.swing.JList<String> lstPuntaje;
    private javax.swing.JTextField txtBien;
    private javax.swing.JTextField txtMal;
    private javax.swing.JTextField txtPost;
    // End of variables declaration//GEN-END:variables
}
