/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Entidades.Alumno_e6;
import javax.swing.JOptionPane;
import javax.swing.table.*;




/**
 *
 * @author WUSUARIO
 */
public class frmEjercicio6 extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    
    /**
     * Creates new form frmEjercicio6
     */
    public frmEjercicio6() {
        initComponents();
        setLocationRelativeTo(this);
        setSize(510,480);
        String titulos[]={"Alumno","I Unidad","II Unidad","III Unidad","Promedio","Turno"};
        dtm.setColumnIdentifiers(titulos);
        jTable1.setModel(dtm);
//        Alumno_e6 d = new Alumno_e6("Luis", 10, 5, 7, "tarde");
//        String d[]={};
//        dtm.addRow(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboTurno = new javax.swing.JComboBox<>();
        txtn1 = new javax.swing.JTextField();
        txtn3 = new javax.swing.JTextField();
        txtn2 = new javax.swing.JTextField();
        txtAlu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CALIFICACIONES DEL CURSO DE PROGRAMACION VISUAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setText("Alumno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Nota de la I Unidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Nota de la III Unidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Nota de la II Unidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel6.setText("Turno:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        cboTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Mañana", "Tarde", "Noche" }));
        getContentPane().add(cboTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 140, -1));
        getContentPane().add(txtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, -1));
        getContentPane().add(txtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 90, -1));
        getContentPane().add(txtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, -1));
        getContentPane().add(txtAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 380, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 170));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel7.setText("Total de Alumnos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String datos[]=new String[6];
        int total;
//        double promedio;
        boolean verifica;
        int n1=Integer.parseInt(txtn1.getText());
        int n2=Integer.parseInt(txtn2.getText());
        int n3=Integer.parseInt(txtn3.getText());
        String nombre = txtAlu.getText();
        String turno = cboTurno.getSelectedItem().toString();
        Alumno_e6 oa = new Alumno_e6(nombre, n1, n2, n3, turno);
        
        
        verifica = txtAlu.getText().equals("") || txtn1.getText().equals("")||txtn2.getText().equals("")||txtn3.getText().equals("");
        verifica = verifica||cboTurno.getSelectedIndex()==0;
        if(!verifica){
//            promedio = (double)(n1+n2+n3)/(double)3;
            oa.cacular();
            
                
//            datos[0]=txtAlu.getText();
//            datos[1]=txtn1.getText();
//            datos[2]=txtn2.getText();
//            datos[3]=txtn3.getText();
//            datos[4]=String.valueOf(oa.getPromedio());
//            datos[5]=(String)cboTurno.getSelectedItem();
            
            datos[0]=oa.getNombre();
            datos[1]=String.valueOf(oa.getN1());
            datos[2]=String.valueOf(oa.getN2());
            datos[3]=String.valueOf(oa.getN3());
            datos[4]=String.valueOf(oa.getPromedio());
            datos[5]=oa.getTurno();
            
            dtm.addRow(datos);
            txtAlu.setText("");
            txtn1.setText("");
            txtn2.setText("");
            txtn3.setText("");
            cboTurno.setSelectedIndex(0);
            
        }else{
            JOptionPane.showMessageDialog(null, "Falta el ingreso del algun dato");
        }
        total=dtm.getRowCount();
        txtTotal.setText(String.valueOf(total));
//        Alumno_e6 oa = new Alumno_e6(nombre, n1, n2, n3, turno);
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void Eliminar(){
        int fila,total;
        fila=jTable1.getSelectedRow();
        if(fila>=0){
            dtm.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una fila de la Tabla para elegir");
        }
        total=dtm.getRowCount();
        txtTotal.setText(String.valueOf(total));
       
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlu;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn2;
    private javax.swing.JTextField txtn3;
    // End of variables declaration//GEN-END:variables
}
