/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author WUSUARIO
 */
public class frmEjercicio11 extends javax.swing.JFrame {

    /**
     * Creates new form frmEjercicio11
     */
    public frmEjercicio11() {
        initComponents();
        setLocationRelativeTo(this);
        setSize(680,420);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar_principal = new javax.swing.JMenuBar();
        jMenu1_archivos = new javax.swing.JMenu();
        jMenuItem_abrir = new javax.swing.JMenuItem();
        jMenuItem_guardar = new javax.swing.JMenuItem();
        jMenuItem_imprimir = new javax.swing.JMenuItem();
        jMenu_basico = new javax.swing.JMenu();
        jMenuItem_histograma = new javax.swing.JMenuItem();
        jMenuItem_imagenc = new javax.swing.JMenuItem();
        jMenuItem_conversiong = new javax.swing.JMenuItem();
        jMenuItem_negativo = new javax.swing.JMenuItem();
        jMenuItem_binarizar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1_archivos.setText("Archivos");

        jMenuItem_abrir.setText("Abrir");
        jMenu1_archivos.add(jMenuItem_abrir);

        jMenuItem_guardar.setText("Guardar");
        jMenu1_archivos.add(jMenuItem_guardar);

        jMenuItem_imprimir.setText("Imprimir");
        jMenuItem_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_imprimirActionPerformed(evt);
            }
        });
        jMenu1_archivos.add(jMenuItem_imprimir);

        jMenuBar_principal.add(jMenu1_archivos);

        jMenu_basico.setText("Basico");

        jMenuItem_histograma.setText("Histograma");
        jMenu_basico.add(jMenuItem_histograma);

        jMenuItem_imagenc.setText("Imagen completa");
        jMenu_basico.add(jMenuItem_imagenc);

        jMenuItem_conversiong.setText("Coversion a gris");
        jMenu_basico.add(jMenuItem_conversiong);

        jMenuItem_negativo.setText("Negativo");
        jMenu_basico.add(jMenuItem_negativo);

        jMenuItem_binarizar.setText("Binarizar");
        jMenuItem_binarizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_binarizarActionPerformed(evt);
            }
        });
        jMenu_basico.add(jMenuItem_binarizar);

        jMenuBar_principal.add(jMenu_basico);

        jMenu1.setText("Filtros");

        jMenu3.setText("Espaciales");

        jMenu5.setText("Paso Alto");

        jMenu7.setText("Realce");

        jMenuItem1.setText("Sharpen 1");
        jMenu7.add(jMenuItem1);

        jMenuItem2.setText("Sharper 2");
        jMenu7.add(jMenuItem2);

        jMenuItem3.setText("Sharper 3");
        jMenu7.add(jMenuItem3);

        jMenu5.add(jMenu7);

        jMenu8.setText("Dteccion de borders");
        jMenu5.add(jMenu8);

        jMenu3.add(jMenu5);

        jMenu6.setText("Paso Bajo");
        jMenu3.add(jMenu6);

        jMenu9.setText("Personal");
        jMenu3.add(jMenu9);

        jMenu1.add(jMenu3);

        jMenu4.setText("Frecuenciales");
        jMenu1.add(jMenu4);

        jMenuBar_principal.add(jMenu1);

        jMenu2.setText("Transformadas");

        jMenu10.setText("Fourir");

        jMenuItem4.setText("Magnitud");
        jMenu10.add(jMenuItem4);

        jMenuItem5.setText("Fase");
        jMenu10.add(jMenuItem5);

        jMenuItem6.setText("Potencia");
        jMenu10.add(jMenuItem6);

        jMenu2.add(jMenu10);

        jMenu11.setText("Coseno");
        jMenu2.add(jMenu11);

        jMenu12.setText("Gabor");
        jMenu2.add(jMenu12);

        jMenu13.setText("Wvelet");
        jMenu2.add(jMenu13);

        jMenuBar_principal.add(jMenu2);

        setJMenuBar(jMenuBar_principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_imprimirActionPerformed

    private void jMenuItem_binarizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_binarizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_binarizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu1_archivos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar_principal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_abrir;
    private javax.swing.JMenuItem jMenuItem_binarizar;
    private javax.swing.JMenuItem jMenuItem_conversiong;
    private javax.swing.JMenuItem jMenuItem_guardar;
    private javax.swing.JMenuItem jMenuItem_histograma;
    private javax.swing.JMenuItem jMenuItem_imagenc;
    private javax.swing.JMenuItem jMenuItem_imprimir;
    private javax.swing.JMenuItem jMenuItem_negativo;
    private javax.swing.JMenu jMenu_basico;
    // End of variables declaration//GEN-END:variables
}
