/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Alumno_e5;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author WUSUARIO
 */
public class frmEjercicio5 extends javax.swing.JFrame {
    private DefaultListModel model1 = new DefaultListModel();
    private DefaultListModel model2 = new DefaultListModel();
    private DefaultListModel model3 = new DefaultListModel();
    private DefaultListModel model4 = new DefaultListModel();
    
    
    /**
     * Creates new form frmEjercicio5
     */
    public frmEjercicio5() {
        initComponents();
        setLocationRelativeTo(this);
        setSize(610,510);
        lstCurOfer.setModel(model1);
        lstCostos.setModel(model2);
        lstCurEsco.setModel(model3);
        lstCos.setModel(model4);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAlu = new javax.swing.JTextField();
        cboCategorias = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCurOfer = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCostos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCurEsco = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstCos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboFPago = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        txtCTotal = new javax.swing.JTextField();
        txtMen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ALUMNO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Categoria de Cursos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txtAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 260, -1));

        cboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Diseño Grafico", "Diseño Web", "Ofimatica", "Lenguajes de Programacion", "Sistemas Operativos" }));
        cboCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriasActionPerformed(evt);
            }
        });
        getContentPane().add(cboCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 180, -1));

        jLabel3.setText("Cursos Ofertados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Costo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel5.setText("Cursos Escogidos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel6.setText("Costo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        lstCurOfer.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCurOferValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCurOfer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 150));

        jScrollPane2.setViewportView(lstCostos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 60, 150));

        lstCurEsco.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCurEscoValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCurEsco);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 110, 150));

        jScrollPane4.setViewportView(lstCos);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 60, 150));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel7.setText("Forma de Pago:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        cboFPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Contado", "Credito" }));
        getContentPane().add(cboFPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 100, -1));

        jButton3.setText("CALCULAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jButton4.setText("BORRRAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jButton5.setText("CERRAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        jLabel8.setText("Matricula");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jLabel9.setText("CostoTtotal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabel10.setText("PagoMensual");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));
        getContentPane().add(txtMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 90, -1));
        getContentPane().add(txtCTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 100, -1));
        getContentPane().add(txtMen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriasActionPerformed

          presentar();
    }//GEN-LAST:event_cboCategoriasActionPerformed

    public void presentar(){
        int indice;
        indice = cboCategorias.getSelectedIndex();
        switch(indice){
            case 0:
                model1.clear();model2.clear();
                break;
            case 1:
                model1.clear();model2.clear();
                model1.addElement("Corel Draw"); model2.addElement("180");
                model1.addElement("Photo Shop"); model2.addElement("170");
                break;
            case 2:
                model1.clear();model2.clear();
                model1.addElement("Diseño con HTML"); model2.addElement("100");
                model1.addElement("JavaScript"); model2.addElement("120");
                model1.addElement("PHP Y MYsQl"); model2.addElement("180");
                model1.addElement("ASP .NET"); model2.addElement("180");
                break;
            case 3:
                model1.clear();model2.clear();
                model1.addElement("Word"); model2.addElement("120");
                model1.addElement("Excel"); model2.addElement("130");
                model1.addElement("Power Point"); model2.addElement("100");
                model1.addElement("VIsio"); model2.addElement("110");
                break;
            case 4:
                model1.clear();model2.clear();
                model1.addElement("Visual Basic .Net"); model2.addElement("240");
                model1.addElement("Visual Java"); model2.addElement("290");
                model1.addElement("Power Builder"); model2.addElement("230");
                model1.addElement("Visual c# .Net"); model2.addElement("220");
                break;
            case 5:
                model1.clear();model2.clear();
                model1.addElement("Windos Vista"); model2.addElement("160");
                model1.addElement("Linux"); model2.addElement("180");
                break;
                
        }
    }
    
    private void lstCurOferValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCurOferValueChanged
        int indice = lstCurOfer.getSelectedIndex();
        lstCostos.setSelectedIndex(indice);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_lstCurOferValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String curso,costo;
        int total,i;
        curso = (String)lstCurOfer.getSelectedValue();
        costo = (String)lstCostos.getSelectedValue();
        model3.addElement(curso);
        model4.addElement(costo);
        jButton1.setEnabled(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstCurEscoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCurEscoValueChanged
        int indice = lstCurEsco.getSelectedIndex();
        lstCos.setSelectedIndex(indice);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_lstCurEscoValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int indice = lstCurEsco.getSelectedIndex();
        model3.remove(indice);
        model4.remove(indice);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int cuenta = model3.size(),i;
       float mat=0,ctotal=0,pmen=0;

        
        for(i=0;i<cuenta;i++){
            ctotal = ctotal+Float.parseFloat((String)model4.elementAt(i));
        }
        if(ctotal==0){
            JOptionPane.showMessageDialog(null,"Selecciona y agrega el menos un curso");
            return;
        }
        if(cuenta==1) mat =ctotal+0.8f;
        if(cuenta==2) mat =ctotal+0.6f;
        if(cuenta>=3) mat =ctotal+0.5f;

        
        String nombre= txtAlu.getText();
        String categoria = cboCategorias.getSelectedItem().toString();
        String FPago = cboFPago.getSelectedItem().toString();
        
        Alumno_e5 oa = new Alumno_e5(nombre, categoria, FPago,ctotal,mat);
        oa.Calcular(ctotal);

        txtMat.setText(String.valueOf((int) oa.getMatricula()));
        txtCTotal.setText(String.valueOf( (int)oa.getCostoT()));
        txtMen.setText(String.valueOf((int)oa.getPsgoM()));
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void borrar(){
        txtAlu.setText("");
        txtCTotal.setText("");
        txtMat.setText("");
        txtMen.setText("");
        cboCategorias.setSelectedItem("<Seleccionar>");
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

          borrar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCategorias;
    private javax.swing.JComboBox<String> cboFPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstCos;
    private javax.swing.JList<String> lstCostos;
    private javax.swing.JList<String> lstCurEsco;
    private javax.swing.JList<String> lstCurOfer;
    private javax.swing.JTextField txtAlu;
    private javax.swing.JTextField txtCTotal;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtMen;
    // End of variables declaration//GEN-END:variables
}
