
package Fomularios;

import Controlador.TLista;
import Entidades.Asalariado;
import Entidades.AsalariadoPorComision;
//import Entidades.Consultor;
import Entidades.Empleado;
import Entidades.PorComision;
import Entidades.PorHoras;
//import Entidades.Trabajador;

import java.awt.Color; //Color
import javax.swing.JOptionPane;

/**
 * @date 11/03/2021 10:30
 * @author Jeremy Prieto
 */
public class frmEditEmpleado extends javax.swing.JFrame {

    public String Funcion;
    /**
     * Creates new form frmEditPersona
     */
    public frmEditEmpleado(String f) {
        initComponents();
        this.Funcion=f;
        this.getContentPane().setBackground(new Color( 59, 177, 198 ));  //Color del jframe
        setSize(380,540);
        setLocationRelativeTo(this);
    }

    //Metodo para llenar con los datos el formulario al abrirlo
    /**
     * @date 11/03/2021
     * @autor Jeremy Prieto 
     */
    public void setDatosE(Empleado oe){
        jTextField1.setText(oe.getCedula());
        jTextField3.setText(oe.getNombres());
        jComboBox1.setSelectedItem(String.valueOf(oe.getSexo()));
        jTextField4.setText(oe.getApellidos());
        
        
        

        jTextField8.setText(String.valueOf(oe.getEdad()));

        jComboBox2.setSelectedItem(oe.getTipo());
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Insertar Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ced:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Edad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Tipo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno", "Asalariado", "AsalariadoPorComision", "PorComision", "PorHoras" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Sueldo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Ventas:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Tarifa:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 130, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 130, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Horas:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno", "M", "F" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jTextField1.getText().equals("") && !jTextField3.getText().equals("")&& !jTextField4.getText().equals("")&& jComboBox2.getSelectedIndex()>0){
            String ced = jTextField1.getText();
            String nom = jTextField3.getText();
            String ape = jTextField4.getText();
            char sex = jComboBox1.getSelectedItem().toString().charAt(0);
            int eda = Integer.parseInt(jTextField8.getText());
            String tip = jComboBox2.getSelectedItem().toString();
            double sue = Double.parseDouble(jTextField2.getText());
            double ven = Double.parseDouble(jTextField5.getText());
            double tar = Double.parseDouble(jTextField6.getText());
            double hor = Double.parseDouble(jTextField9.getText());
           
            if(jComboBox2.getSelectedItem().toString().equals("Asalariado")){
                Empleado oea = new Asalariado(ced, nom, ape, sex, eda, tip, sue);
                if(Funcion.equals("Insertar")){
                    TLista.Insert(oea);
                }else{ 
                    int pos = TLista.Buscar(ced);
                    TLista.EditEmpleado(pos, oea);
                }
                frmAdminEmpleado.MostrarDatos();
                this.dispose();
            }
            if(jComboBox2.getSelectedItem().toString().equals("AsalariadoPorComision")){
                Empleado oeac = new AsalariadoPorComision(ced, nom, ape, sex, eda, tip, sue, ven);
                if(Funcion.equals("Insertar")){
                    TLista.Insert(oeac);
                }else{ 
                    int pos = TLista.Buscar(ced);
                    TLista.EditEmpleado(pos, oeac);
                }
                frmAdminEmpleado.MostrarDatos();
                this.dispose();
            }
            if(jComboBox2.getSelectedItem().toString().equals("PorComision")){
                Empleado oec = new PorComision(ced, nom, ape, sex, eda, tip, tar, ven, sue);
                if(Funcion.equals("Insertar")){
                    TLista.Insert(oec);
                }else{ 
                    int pos = TLista.Buscar(ced);
                    TLista.EditEmpleado(pos, oec);
                }
                frmAdminEmpleado.MostrarDatos();
                this.dispose();
            }
            if(jComboBox2.getSelectedItem().toString().equals("PorHoras")){
                Empleado oeh = new PorHoras(ced, nom, ape, sex, eda, tip, hor, sue);
                if(Funcion.equals("Insertar")){
                    TLista.Insert(oeh);
                }else{ 
                    int pos = TLista.Buscar(ced);
                    TLista.EditEmpleado(pos, oeh);
                }
                frmAdminEmpleado.MostrarDatos();
                this.dispose();
            }
            
     
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese correctamente los datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
//    //Cambia los dos ultimos labels para el tipo de dato correspondiente a ingresar respecto al tipo de trabajador(jcombobox)
//        if(jComboBox2.getSelectedItem().toString().equals("Asalariado"))
//        {
////            jTextField2.setEnabled(true);
//            jTextField5.setEnabled(false);
//            jTextField6.setEnabled(false);
//            jTextField9.setEnabled(false);
////            jLabel9.setText("...");
////            jLabel10.setText("...");
////            jLabel11.setText("...");
//        }
//        if(jComboBox2.getSelectedItem().toString().equals("AsalariadoPorComision"))
//        {
////            jTextField2.setEnabled(true);
////            jTextField5.setEnabled(true);
//          
//            jTextField6.setEnabled(false);
//            jTextField9.setEnabled(false);
//           
////            jLabel10.setText("...");
////            jLabel11.setText("...");
//        }
//        if(jComboBox2.getSelectedItem().toString().equals("PorComision"))
//        {
////            jTextField5.setEnabled(true);
////            jTextField6.setEnabled(true);
//            
//            jTextField2.setEnabled(false);
//         
//            jTextField9.setEnabled(false);
//            
////            jLabel8.setText("...");
////            
////            jLabel11.setText("...");
//        }
//        if(jComboBox2.getSelectedItem().toString().equals("PorHoras"))
//        {
////            jTextField2.setEnabled(true);
////            jTextField9.setEnabled(true);
//            jTextField5.setEnabled(false);
//            jTextField6.setEnabled(false);
//            
////            jLabel9.setText("...");
////            jLabel10.setText("...");
           
        //}
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditEmpleado("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
