/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controlador.TListaCamion;
import Controlador.TListaCliente;
import Controlador.TListaEncomienda;
import Controlador.TListaGuiaEnvio;
import Entidades.Camiones;
import Entidades.Clientes;
import Entidades.Encomiendas;
import Entidades.GuiaEnvio;
import javax.swing.JOptionPane;

/**
 *
 * @author Félix
 */
public class frmInsertarGuiaEnvio extends javax.swing.JFrame {

    /**
     * Creates new form frmInsertarGuiaEnvio
     */
    public String funcion;
    public frmInsertarGuiaEnvio(String func) {
        initComponents();
        this.funcion = func;
        setSize(560, 400);
        setLocationRelativeTo(this);
        
        ListarDatos();
    }
    
    private void ListarDatos(){
        
        jComboBox1.addItem("<Seleccione Cliente>");
        for (int i = 0; i < TListaCliente.Count(); i++) {
            Clientes ob = TListaCliente.obtenerCliente(i);
            
            int pos = TListaGuiaEnvio.BuscarCliente(ob.getCodigo());
            
            if(pos == -1){
                jComboBox1.addItem(ob.getNombres());
            }
            
        }
        
        jComboBox2.addItem("<Seleccione Placa>");
        for (int i = 0; i < TListaCamion.Count(); i++) {
            Camiones ob = TListaCamion.obtenerCamion(i);
            if(ob.getEstado().equals("DISPONIBLE")){
                jComboBox2.addItem(ob.getPlaca());
            }
        }
        
        jTable1.setModel(TListaGuiaEnvio.tablaModelEncomiendaTemp());
        
    }

    public static void setDatos(Encomiendas oe){
        double peso = Double.parseDouble(jTextField3.getText());
        if (oe.getPeso() <= peso){
            
            TListaGuiaEnvio.AgregaEncomiendaTemp(oe);
            jTable1.setModel(TListaGuiaEnvio.tablaModelEncomiendaTemp());
            
        }else{
            JOptionPane.showMessageDialog(null, "El peso de la encomienda supera al peso maximo del camion");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnAsignar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Camión");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel4.setText("Peso Máximo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel5.setText("Disponible");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jTextField2.setText("0");
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 80, -1));

        jTextField3.setText("0");
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 80, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 240, -1));

        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, -1));

        jLabel7.setText("Codigo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, -1));

        btnAsignar.setText("Asignar Encomienda");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 80, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 500, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex() > 0){
            int pos = TListaCamion.BuscarCamionPlaca(jComboBox2.getSelectedItem().toString());
            Camiones ob = TListaCamion.obtenerCamion(pos);
            int idCamion        = ob.getId();
            String placa        = ob.getPlaca();
            double pesoMaximo   = ob.getPeso();
            double pesoOcupado  = TListaGuiaEnvio.PesoOcupado(idCamion);
            double pesoDisponible = pesoMaximo - pesoOcupado;

            jTextField2.setText(String.valueOf(pesoMaximo));
            jTextField3.setText(String.valueOf(pesoDisponible));
            
            if(pesoDisponible == 0){
                btnGuardar.setEnabled(false);
            }else{
                btnGuardar.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
       frmListaEncomienda frmVentana = new frmListaEncomienda();
       frmVentana.setVisible(true);
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(!jTextField1.getText().equals("") && jComboBox1.getSelectedIndex() > 0 && jComboBox2.getSelectedIndex() > 0){

            try {

                String Codigo       = jTextField1.getText();

                String Nombres      = jComboBox1.getSelectedItem().toString();
                int posCliente      = TListaCliente.BuscarNombre(Nombres);
                Clientes objCliente = TListaCliente.obtenerCliente(posCliente);
                String CodCliente   = objCliente.getCodigo();
                
                String Placa        = jComboBox2.getSelectedItem().toString();
                int posCamion       = TListaCamion.BuscarCamionPlaca(Placa);
                Camiones objCamion  = TListaCamion.obtenerCamion(posCamion);
                int IdCamion        = objCamion.getId();
                
                GuiaEnvio op = new GuiaEnvio(Codigo, CodCliente, IdCamion,"ENVIADO");
                

                if(funcion.equals("Insertar")){
                    
                    TListaGuiaEnvio.Agregar(op);
                    TListaGuiaEnvio.ActualizarEstadoEncomienda(Codigo, "ENVIADO");
                    TListaGuiaEnvio.AtualizarEstadoCamion(IdCamion, "OCUPADO");
                    
                }else{
                    TListaGuiaEnvio.Actualizar(op, TListaEncomienda.BuscarEncomienda(Codigo));
                }

                frmAdminGuiaEnvio.ListarDatos();
                
                TListaGuiaEnvio.LimpiarEncomiendaTemp();
                
                this.dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }else{
            JOptionPane.showMessageDialog(null, "Ingrese correctamente los datos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInsertarGuiaEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInsertarGuiaEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInsertarGuiaEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInsertarGuiaEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInsertarGuiaEnvio("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
