/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controlador.TListaCamion;
import Controlador.TListaCliente;
import Controlador.TListaEncomienda;
import Entidades.Camiones;
import Entidades.Clientes;
import Entidades.Encomiendas;

/**
 *
 * @author Félix
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        setSize(720, 500);
        setLocationRelativeTo(this);
        ListarDatos();
    }

    private static void ListarDatos(){
        TListaCliente.Agregar(new Clientes("1", "4654", "ANDRES", "51654", "GUABO"));
        TListaCliente.Agregar(new Clientes("2", "7932", "DANIEL", "51654", "MACHALA"));
        TListaCliente.Agregar(new Clientes("3", "1654", "CARLOS", "51654", "MACHALA"));
        TListaCliente.Agregar(new Clientes("4", "9879", "JOSE", "51654", "SANTA ROSA"));
        TListaCliente.Agregar(new Clientes("5", "7943", "PEDRO", "51654", "PASAJE"));
        
        TListaCamion.Agregar(new Camiones(1, "ABC-125", "MIGUEL", 150, "DISPONIBLE"));
        TListaCamion.Agregar(new Camiones(2, "OBA-126", "ARMANDO", 250, "DISPONIBLE"));
        TListaCamion.Agregar(new Camiones(3, "LJA-127", "MANUEL", 200, "DISPONIBLE"));
        TListaCamion.Agregar(new Camiones(4, "PCA-128", "JOSE", 200, "DISPONIBLE"));
        
        TListaEncomienda.Agregar(new Encomiendas("1", 20, "GUABO", 10, "PENDIENTE",""));
        TListaEncomienda.Agregar(new Encomiendas("2", 30, "PONCE E.", 15, "PENDIENTE",""));
        TListaEncomienda.Agregar(new Encomiendas("3", 10, "NARANJAL", 5, "PENDIENTE",""));
        TListaEncomienda.Agregar(new Encomiendas("4", 70, "BALAO", 25, "PENDIENTE",""));
        TListaEncomienda.Agregar(new Encomiendas("5", 80, "DURAN", 30, "PENDIENTE",""));
        TListaEncomienda.Agregar(new Encomiendas("6", 30, "PUERTO INCA", 12, "PENDIENTE",""));
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        mnuAdminCliente = new javax.swing.JMenuItem();
        mnuAdminCamiones = new javax.swing.JMenuItem();
        mnuAdminEncomiendas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jMenu5.setText("Gestion");

        mnuAdminCliente.setText("Admin Cliente");
        mnuAdminCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminClienteActionPerformed(evt);
            }
        });
        jMenu5.add(mnuAdminCliente);

        mnuAdminCamiones.setText("Admin Camiones");
        mnuAdminCamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminCamionesActionPerformed(evt);
            }
        });
        jMenu5.add(mnuAdminCamiones);

        mnuAdminEncomiendas.setText("Admin Encomiendas");
        mnuAdminEncomiendas.setToolTipText("");
        mnuAdminEncomiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminEncomiendasActionPerformed(evt);
            }
        });
        jMenu5.add(mnuAdminEncomiendas);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Encomiendas");

        jMenuItem4.setText("Guia envio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Control enc.");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reportes");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAdminEncomiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminEncomiendasActionPerformed
        // TODO add your handling code here:
        frmAdminEncomiendas frmVentana = new frmAdminEncomiendas();
        frmVentana.setVisible(true);
    }//GEN-LAST:event_mnuAdminEncomiendasActionPerformed

    private void mnuAdminClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminClienteActionPerformed
        // TODO add your handling code here:
        frmAdminClientes frmVentana = new frmAdminClientes();
        frmVentana.setVisible(true);
    }//GEN-LAST:event_mnuAdminClienteActionPerformed

    private void mnuAdminCamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminCamionesActionPerformed
        // TODO add your handling code here:
        frmAdminCamion frmVentana = new frmAdminCamion();
        frmVentana.setVisible(true);
    }//GEN-LAST:event_mnuAdminCamionesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        frmAdminGuiaEnvio frmVentana = new frmAdminGuiaEnvio();
        frmVentana.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        frmControlEncomienda frmVentana = new frmControlEncomienda();
        frmVentana.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mnuAdminCamiones;
    private javax.swing.JMenuItem mnuAdminCliente;
    private javax.swing.JMenuItem mnuAdminEncomiendas;
    // End of variables declaration//GEN-END:variables
}
